name: CI - Build Flutter (Debug)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
#  build_ios:
#    name: Build Flutter iOS (Debug)
#    runs-on: macOS-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-java@v1
#      with:
#        java-version: '12.x'
#    - uses: subosito/flutter-action@v2
#      with:
#          channel: 'stable'
#    - run: flutter pub get
#    - run: flutter clean
#    - run: flutter build ios --debug --no-codesign
  build_apk:
    name: Build Flutter Android (Debug)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --debug
