# Copyright (c) 2023, StarIC, author: Justin Y. Kim

name: sopep_app
description: Engineering app used to test the sOPEP device.
version: 0.3.5+13
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_reactive_ble: ^5.2.0
  functional_data: ^1.0.0
  intl: ^0.17.0
  cbor: ^5.1.2
  crclib: ^3.0.0
  cobs2: ^0.2.0
  wakelock: ^0.6.2
  provider: ^6.0.1
  package_info_plus: ^3.0.3
  flutter_spinkit: ^5.2.0
  permission_handler: ^10.4.2
  path_provider: ^2.1.1
  csv: ^5.1.1
  # Firebase and cloud related dependencies
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.0
  cloud_functions: ^4.3.4
  cloud_firestore: ^4.8.3

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.1.0
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
